SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 01
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;

# SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,
#        SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
# FROM BOOK AS B
# INNER JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
# INNER JOIN BOOK_SALES AS BS ON B.BOOK_ID = BS.BOOK_ID
# WHERE YEAR(BS.SALES_DATE) = 2022 AND MONTH(BS.SALES_DATE) = 01
# GROUP BY A.AUTHOR_NAME, B.CATEGORY
# ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;


