WITH PARENT_COLONY AS (
SELECT B.ID
FROM ECOLI_DATA A
JOIN ECOLI_DATA B
ON A.ID = B.PARENT_ID
WHERE A.PARENT_ID IS NULL)

SELECT B.ID
FROM PARENT_COLONY A
JOIN ECOLI_DATA B
ON A.ID = B.PARENT_ID
ORDER BY ID;