-- 코드를 입력하세요
WITH RENTAL AS (
SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE)+1 AS DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)

SELECT CAR_ID, ROUND(AVG(DATE),1) AS AVERAGE_DURATION
FROM RENTAL
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY 2 DESC, 1 DESC;