WITH FIVE_RENTAL AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)

SELECT 
    MONTH(START_DATE) AS MONTH, 
    T1.CAR_ID,
    COUNT(T1.CAR_ID) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T1
WHERE 
    DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    AND T1.CAR_ID IN (SELECT CAR_ID FROM FIVE_RENTAL)
GROUP BY 
    T1.CAR_ID, 
    MONTH(START_DATE)
HAVING COUNT(T1.CAR_ID) >= 1
ORDER BY 
    MONTH, 
    CAR_ID DESC;