SELECT YEAR(e.DIFFERENTIATION_DATE) AS YEAR, (p.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV, e.ID
FROM ECOLI_DATA e
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) as MAX_SIZE
     FROM ECOLI_DATA
     GROUP BY YEAR) p ON YEAR(e.DIFFERENTIATION_DATE) = p.YEAR
ORDER BY YEAR, YEAR_DEV;