-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_PRICE
FROM BOOK B
JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.CATEGORY
ORDER BY CATEGORY;

# SELECT B.CATEGORY, COUNT(S.SALES)
# FROM BOOK B
# JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
# WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
# GROUP BY B.CATEGORY
# ORDER BY CATEGORY;

# SELECT *
# FROM BOOK B
# JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID;
